name: Workflow | Deploy backend

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string

jobs:
  cluster:
    name: cluster
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-cdk-stack
        with:
          account: ${{ inputs.account }}
          region: ${{ inputs.region }}
          stacks: imported-hypurr-liquidator-cluster

  price-pusher:
    needs:
      - cluster
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-cdk-stack
        with:
          account: ${{ inputs.account }}
          region: ${{ inputs.region }}
          stacks: hypurr-price-pusher
